### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jbreit88**
# Description

Please check the type of change your PR introduces:
- [ ] Bugfix (change which fixes an issue)
- [ ] Feature (change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

 

 

### Type of change

Please check the relevant option.

- [ ] Non-Breaking Change
- [ ] Breaking change (fix or feature that causes existing functionality to not work as expected)
- [ ] Big Breaking change (this breaks everything and I am sorry)

# Where should reviewers start?

# How Has This Been Tested?

Please check the option(s) that best describe your tests. 

- [ ] New spec files were added
- [ ] Tests were added to existing spec files
- [ ] Some tests were changed
- [ ] No tests were changed
- [ ] All tests were changed (please explain what in God's name happened)

### Tests Description

- Please add further details of your tests here.

# Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have removed all unused code or commented why I left it
- [ ] I have deployed my changes to a test-heroku and they work
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by jbreit88** [comment]
@all-contributors please add @JCNapier for his contributions in tests, reviews, research.

**Comment by JCNapier** [comment]
I am not seeing any collaborators yet in the README. Have any been added yet?

**Comment by jbreit88** [comment]
Lol, trying to get the all-contributors bot to do it automatically. :)

**Comment by JCNapier** [comment]
haha ohhh cool, gotcha. I haven't used that bot yet.

**Comment by jbreit88** [comment]
@all-contributors please add @jbreit88 for his contributions to reviews, research, documentation.

**Comment by jbreit88** [comment]
@all-contributors please add @JCNapier for his contributions in tests, reviews, research.

**Pull request merged**
